-keep class com.eidlink.idocr.sdk.**{*;}
-keep class com.eidlink.idocr.util.DelayUtil{*;}
-keep class com.eidlink.jni.**{*;}
-keep class net.sf.scuba.data.**{*;}
-keep class org.**{*;}
-keep class cn.**{*;}
-keep class com.froad.**{*;}
-keep class com.huawei.**{*;}
-ignorewarnings